[global]
# Streamlit configuration for dashboard deployment

[server]
# Server configuration
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Dashboard theme
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6" 
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
showErrorDetails = false
toolbarMode = "minimal"
